#!ruby

require "whois/api"
require "rack"

arg_options = Rack::Server::Options.new.parse!(ARGV)

environment = ENV["RACK_ENV"] ||= arg_options[:environment] || "development"
default_host = environment == "development" ? "localhost" : "0.0.0.0"

options = {
  environment: environment,
  pid:         nil,
  Port:        9292,
  Host:        default_host,
  AccessLog:   []
}.merge(arg_options)

options[:app] = Whois::Api.new

Rack::Server.start(options)
